name: cat_facts
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.6.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets\images\liquid-effect-background.jpg
  fonts:
    - family: FF Mark Pro
      fonts:
        - asset: assets\fonts\ff_mark_pro.otf
        - asset: assets\fonts\ff_mark_pro_medium.otf
          weight: 500
        - asset: assets\fonts\ff_mark_pro_bold.otf
          weight: 600
